config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  resources :interventions
  resources :quotes
  resources :leads
  resources :employees
  resources :elevators
  resources :customers
  resources :columns
  resources :buildings
  resources :building_details
  resources :batteries
  resources :addresses
  devise_for :users
  resources :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'quotes/request_quote'
  post '/request_quote', to: 'quotes#create'

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  # do not change root path for the mainPage, the home page is now called "mainPage"
  root "application#mainPage"

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  get '/map', to: 'application#factElevator'
  # get '/map', to: 'application#google_map'

  get '/mainPage', to: "application#mainPage"
  get "/request_quote_page", to: "application#request_quote_page"
  get "/residential-services", to: "application#residential-services"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Mysql_record.rb
class MysqlRecord < ApplicationRecord::Base
    # self.abstract_class = true
    establish_connection MYSQL_DATABASE
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :building
    geocoded_by :address
    after_validation :geocode

    def address 
        [number_and_street, city, postal_code, country].compact.join(", ")
    end
end

app/models/battery.rb
class Battery < ApplicationRecord
  # belongs_to :building, class_name: "Building", foreign_key: "building_id"
  # belongs_to :employee
  # has_many :column, class_name: "Column", foreign_key: "battery_id"
  belongs_to :building
  has_many :columns

  # def columns
  #   puts Battery.columns[0]
  #   puts Battery.columns[1]
  #   puts Battery.columns[2]
  #   puts Battery.columns[3]
  # end
end

app/models/building.rb
class Building < ApplicationRecord

    has_many :batteries
    has_many :building_details
    belongs_to :customer
    belongs_to :address
    has_many :fact_interventions, :dependent => :delete_all

    def position
        #puts address.number_and_street
        #{address: address.number_and_street}
        [address.number_and_street ,address.city, address.postal_code, address.country].compact.join(", ")
    end

    # def customer
    #     customer.CompanyName
    # end
end

app/models/column.rb
class Column < ApplicationRecord


    # belongs_to :battery, class_name: "Battery", foreign_key: "battery_id"
    # has_many :elevators, class_name: "Elevator", foreign_key: "column_id"
    belongs_to :battery
    has_many :elevators

    def fromBattery
        Column.battery_id
    end
end

app/models/customer.rb
class Customer < ApplicationRecord

    has_one :user
    has_many :buildings
    has_many :fact_interventions

end

app/models/dim_customer.rb
class DimCustomer < ApplicationRecord
end

app/models/elevator.rb
require 'twilio-ruby'
require 'slack-ruby-client'
class Elevator < ApplicationRecord
    # belongs_to :column, class_name: "Column", foreign_key: "column_id"
    belongs_to :column
    # before_save :intervention
    before_update :intervention, :twilio_sms

    def intervention
        if self.elevator_status_changed?
            puts "%%%%%%%%%%%%%%%%"
            client = Slack::Web::Client.new 
            texte = "The Elevator #{self.id} with Serial Number #{self.serial_nb} changed status from #{self.elevator_status_was} to #{self.elevator_status}"
            client.chat_postMessage(channel: '#eileen-elevator_operations', text: texte, as_user: true)
        end
    end

    def twilio_sms
        if self.elevator_status_changed?
            # if self.elevator_status == 'Intervention'
                # put your own credentials here
            account_sid = ENV['TWILIO_ACCOUNT_SID']
            auth_token = ENV['TWILIO_AUTH_TOKEN']
            puts "$$$$$$$$$$$$"
            # set up a client to talk to the Twilio REST API
            @client = Twilio::REST::Client.new(account_sid, auth_token)
             twilio_phone = ENV['TWILIO_PHONE_NUMBER']
             message = @client.messages.create(
                     body: 'Elevator #{self.id} with Serial Number #{self.serial_nb} requires maintenance.',
                     from: twilio_phone,
                     to: '+15147131412'
                 )
            # end
        end
    end

end

app/models/employee.rb
class Employee < ApplicationRecord
    # has_one :battery
    # belongs_to :user, dependent: :destroy
    has_many :factInterventions

end

app/models/fact_contact.rb
class FactContact < ApplicationRecord
end

app/models/fact_elevator.rb
class FactElevator < ApplicationRecord
end

app/models/fact_quote.rb
class FactQuote < ApplicationRecord
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
    # has_one_attached :contactAttachment
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :employee
  belongs_to :customer, optional: true

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:lastName, :firstName, :title)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/speech_helper.rb
module SpeechHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lastName %>
    <%= form.text_field :lastName %>
  </div>

  <div class="field">
    <%= form.label :firstName %>
    <%= form.text_field :firstName %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Lastname</th>
      <th>Firstname</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.lastName %></td>
        <td><%= employee.firstName %></td>
        <td><%= employee.title %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lastname:</strong>
  <%= @employee.lastName %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @employee.firstName %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.title %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>