config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  resources :interventions
  resources :quotes
  resources :leads
  resources :employees
  resources :elevators
  resources :customers
  resources :columns
  resources :buildings
  resources :building_details
  resources :batteries
  resources :addresses
  devise_for :users
  resources :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'quotes/request_quote'
  post '/request_quote', to: 'quotes#create'

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  # do not change root path for the mainPage, the home page is now called "mainPage"
  root "application#mainPage"

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  get '/map', to: 'application#factElevator'
  # get '/map', to: 'application#google_map'

  get '/mainPage', to: "application#mainPage"
  get "/request_quote_page", to: "application#request_quote_page"
  get "/residential-services", to: "application#residential-services"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/Mysql_record.rb
class MysqlRecord < ApplicationRecord::Base
    # self.abstract_class = true
    establish_connection MYSQL_DATABASE
end

app/models/address.rb
class Address < ApplicationRecord
    has_one :building
    geocoded_by :address
    after_validation :geocode

    def address 
        [number_and_street, city, postal_code, country].compact.join(", ")
    end
end

app/models/battery.rb
class Battery < ApplicationRecord
  # belongs_to :building, class_name: "Building", foreign_key: "building_id"
  # belongs_to :employee
  # has_many :column, class_name: "Column", foreign_key: "battery_id"
  belongs_to :building
  has_many :columns

  # def columns
  #   puts Battery.columns[0]
  #   puts Battery.columns[1]
  #   puts Battery.columns[2]
  #   puts Battery.columns[3]
  # end
end

app/models/building.rb
class Building < ApplicationRecord

    has_many :batteries
    has_many :building_details
    belongs_to :customer
    belongs_to :address
    has_many :fact_interventions, :dependent => :delete_all

    def position
        #puts address.number_and_street
        #{address: address.number_and_street}
        [address.number_and_street ,address.city, address.postal_code, address.country].compact.join(", ")
    end

    # def customer
    #     customer.CompanyName
    # end
end

app/models/column.rb
class Column < ApplicationRecord


    # belongs_to :battery, class_name: "Battery", foreign_key: "battery_id"
    # has_many :elevators, class_name: "Elevator", foreign_key: "column_id"
    belongs_to :battery
    has_many :elevators

    def fromBattery
        Column.battery_id
    end
end

app/models/customer.rb
class Customer < ApplicationRecord

    has_one :user
    has_many :buildings
    has_many :fact_interventions

end

app/models/dim_customer.rb
class DimCustomer < ApplicationRecord
end

app/models/elevator.rb
require 'twilio-ruby'
require 'slack-ruby-client'
class Elevator < ApplicationRecord
    # belongs_to :column, class_name: "Column", foreign_key: "column_id"
    belongs_to :column
    # before_save :intervention
    before_update :intervention, :twilio_sms

    def intervention
        if self.elevator_status_changed?
            puts "%%%%%%%%%%%%%%%%"
            client = Slack::Web::Client.new 
            texte = "The Elevator #{self.id} with Serial Number #{self.serial_nb} changed status from #{self.elevator_status_was} to #{self.elevator_status}"
            client.chat_postMessage(channel: '#eileen-elevator_operations', text: texte, as_user: true)
        end
    end

    def twilio_sms
        if self.elevator_status_changed?
            # if self.elevator_status == 'Intervention'
                # put your own credentials here
            account_sid = ENV['TWILIO_ACCOUNT_SID']
            auth_token = ENV['TWILIO_AUTH_TOKEN']
            puts "$$$$$$$$$$$$"
            # set up a client to talk to the Twilio REST API
            @client = Twilio::REST::Client.new(account_sid, auth_token)
             twilio_phone = ENV['TWILIO_PHONE_NUMBER']
             message = @client.messages.create(
                     body: 'Elevator #{self.id} with Serial Number #{self.serial_nb} requires maintenance.',
                     from: twilio_phone,
                     to: '+15147131412'
                 )
            # end
        end
    end

end

app/models/employee.rb
class Employee < ApplicationRecord
    # has_one :battery
    # belongs_to :user, dependent: :destroy
    has_many :factInterventions

end

app/models/fact_contact.rb
class FactContact < ApplicationRecord
end

app/models/fact_elevator.rb
class FactElevator < ApplicationRecord
end

app/models/fact_quote.rb
class FactQuote < ApplicationRecord
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/models/lead.rb
class Lead < ApplicationRecord
    # has_one_attached :contactAttachment
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one :employee
  belongs_to :customer, optional: true

end

app/controllers/elevators_controller.rb
class ElevatorsController < ApplicationController
  before_action :set_elevator, only: %i[ show edit update destroy ]

  # GET /elevators or /elevators.json
  def index
    @elevators = Elevator.all
  end

  # GET /elevators/1 or /elevators/1.json
  def show
  end

  # GET /elevators/new
  def new
    @elevator = Elevator.new
  end

  # GET /elevators/1/edit
  def edit
  end

  # POST /elevators or /elevators.json
  def create
    @elevator = Elevator.new(elevator_params)

    respond_to do |format|
      if @elevator.save
        format.html { redirect_to elevator_url(@elevator), notice: "Elevator was successfully created." }
        format.json { render :show, status: :created, location: @elevator }
        # client = Slack::Web::Client.new
        # client.auth_test
        # client.chat_postMessage(channel: '#eileen-elevator_operations', text: 'Hello World', as_user: true)
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elevators/1 or /elevators/1.json
  def update
    respond_to do |format|
      if @elevator.update(elevator_params)
        format.html { redirect_to elevator_url(@elevator), notice: "Elevator was successfully updated." }
        format.json { render :show, status: :ok, location: @elevator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @elevator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elevators/1 or /elevators/1.json
  def destroy
    @elevator.destroy

    respond_to do |format|
      format.html { redirect_to elevators_url, notice: "Elevator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_elevator
      @elevator = Elevator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def elevator_params
      params.require(:elevator).permit(:column_id, :serial_nb, :model, :elevator_status, :date_commissioning, :date_last_inspection, :certificate_inspection, :information, :notes)
    end
end

app/helpers/elevators_helper.rb
module ElevatorsHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/speech_helper.rb
module SpeechHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/elevators/_form.html.erb
<%= form_with(model: elevator, local: true) do |form| %>
  <% if elevator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(elevator.errors.count, "error") %> prohibited this elevator from being saved:</h2>

      <ul>
      <% elevator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :column_id %>
    <%= form.text_field :column_id %>
  </div>

  <div class="field">
    <%= form.label :serial_nb %>
    <%= form.number_field :serial_nb %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model %>
  </div>

  <div class="field">
    <%= form.label :elevator_status %>
    <%= form.text_field :elevator_status %>
  </div>

  <div class="field">
    <%= form.label :date_commissioning %>
    <%= form.datetime_select :date_commissioning %>
  </div>

  <div class="field">
    <%= form.label :date_last_inspection %>
    <%= form.datetime_select :date_last_inspection %>
  </div>

  <div class="field">
    <%= form.label :certificate_inspection %>
    <%= form.text_field :certificate_inspection %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_area :information %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/elevators/edit.html.erb
<h1>Editing Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Show', @elevator %> |
<%= link_to 'Back', elevators_path %>

app/views/elevators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elevators</h1>

<table>
  <thead>
    <tr>
      <th>Column</th>
      <th>Serial nb</th>
      <th>Model</th>
      <th>Elevator Status</th>
      <th>Date commissioning</th>
      <th>Date last inspection</th>
      <th>Certificate inspection</th>
      <th>Information</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @elevators.each do |elevator| %>
      <tr>
        <td><%= elevator.column %></td>
        <td><%= elevator.serial_nb %></td>
        <td><%= elevator.model %></td>
        <td><%= elevator.elevator_status %></td>
        <td><%= elevator.date_commissioning %></td>
        <td><%= elevator.date_last_inspection %></td>
        <td><%= elevator.certificate_inspection %></td>
        <td><%= elevator.information %></td>
        <td><%= elevator.notes %></td>
        <td><%= link_to 'Show', elevator %></td>
        <td><%= link_to 'Edit', edit_elevator_path(elevator) %></td>
        <td><%= link_to 'Destroy', elevator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Elevator', new_elevator_path %>

app/views/elevators/new.html.erb
<h1>New Elevator</h1>

<%= render 'form', elevator: @elevator %>

<%= link_to 'Back', elevators_path %>

app/views/elevators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Column:</strong>
  <%= @elevator.column %>
</p>

<p>
  <strong>Serial nb:</strong>
  <%= @elevator.serial_nb %>
</p>

<p>
  <strong>Model:</strong>
  <%= @elevator.model %>
</p>

<p>
  <strong>Status:</strong>
  <%= @elevator.elevator_status %>
</p>

<p>
  <strong>Date commissioning:</strong>
  <%= @elevator.date_commissioning %>
</p>

<p>
  <strong>Date last inspection:</strong>
  <%= @elevator.date_last_inspection %>
</p>

<p>
  <strong>Certificate inspection:</strong>
  <%= @elevator.certificate_inspection %>
</p>

<p>
  <strong>Information:</strong>
  <%= @elevator.information %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @elevator.notes %>
</p>

<%= link_to 'Edit', edit_elevator_path(@elevator) %> |
<%= link_to 'Back', elevators_path %>