config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"

  resources :interventions
  resources :quotes
  resources :leads
  resources :employees
  resources :elevators
  resources :customers
  resources :columns
  resources :buildings
  resources :building_details
  resources :batteries
  resources :addresses
  devise_for :users
  resources :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'quotes/request_quote'
  post '/request_quote', to: 'quotes#create'

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  # do not change root path for the mainPage, the home page is now called "mainPage"
  root "application#mainPage"

  get 'leads/leads_quote'
  post '/leads_quote', to: 'leads#create'

  get '/map', to: 'application#factElevator'
  # get '/map', to: 'application#google_map'

  get '/mainPage', to: "application#mainPage"
  get "/request_quote_page", to: "application#request_quote_page"
  get "/residential-services", to: "application#residential-services"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/intervention.rb
class Intervention < ApplicationRecord
end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_action :set_intervention, only: %i[ show edit update destroy ]
  respond_to :html, :json

  require 'rest-client'
  require 'json'

  # GET /interventions or /interventions.json
  def index
    @interventions = Intervention.all
  end

  # GET /interventions/1 or /interventions/1.json
  def show
  end

  # GET /interventions/new
  def new
    @intervention = Intervention.new
    @customers = Customer.all
    @employee = Employee.all
    @author = current_user.id


  end

  # GET /interventions/1/edit
  def edit
  end

  # POST /interventions or /interventions.json
  def create
    @intervention = Intervention.new(intervention_params)

    respond_to do |format|
      if @intervention.save


        # Find the names to send in description
        author = Employee.find(@intervention.Author)
        authorName = author.firstName + " " + author.lastName
        customer = Customer.find(@intervention.CustomerID)
        customerName = customer.CompanyName
        employee = Employee.find(@intervention.EmployeeID)
        employeeName = employee.firstName + " " + employee.lastName

        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully created." }
        format.json { render :show, status: :created, location: @intervention }


              # ------- FreshDesk -------

        # Your freshdesk domain
        freshdesk_domain = 'codeboxx-assist'

        # It could be either your user name or api_key.
        user_name_or_api_key = ENV['FRESHDESK_API_KEY']

        # If you have given api_key, then it should be x. If you have given user name, it should be password
        password_or_x = 'x'

        #attachments should be of the form array of Hash with files mapped to the key 'resource'.
        multipart_payload = JSON.generate({
                      status: 2,
                      priority: 1,
                      type: "Incident",
                      email: "support@codeboxx-assist.freshdesk.com",
                      description:
                      "Requester: " + authorName + ",\n
                      Client: " + customerName + ",\n
                      Building ID: #{@intervention.BuildingID},\n
                      Battery ID: #{@intervention.BatteryID},\n
                      Column ID: #{@intervention.ColumnID},\n
                      Elevator ID: #{@intervention.ElevatorID},\n
                      Assigned Employee: " + employeeName + ",\n
                      Description: #{@intervention.Report}",
                      subject: "Building No." + @intervention.BuildingID.to_s + " requires intervention"

        })

        freshdesk_api_path = 'api/v2/tickets'

        freshdesk_api_url  = "https://#{freshdesk_domain}.freshdesk.com/#{freshdesk_api_path}"

        site = RestClient::Resource.new(freshdesk_api_url, user_name_or_api_key, password_or_x)

        begin
          response = site.post(multipart_payload, :content_type => 'application/json')
          puts "response_code: #{response.code} \nLocation Header: #{response.headers[:Location]} \nresponse_body: #{response.body} \n"
          rescue RestClient::Exception => exception
          puts 'API Error: Your request is not successful. If you are not able to debug this error properly, mail us at support@freshdesk.com with the follwing X-Request-Id'
          puts "X-Request-Id : #{exception.response.headers[:x_request_id]}"
          puts "Response Code: #{exception.response.code} \nResponse Body: #{exception.response.body} \n"
        end


      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interventions/1 or /interventions/1.json
  def update
    respond_to do |format|
      if @intervention.update(intervention_params)
        format.html { redirect_to intervention_url(@intervention), notice: "Intervention was successfully updated." }
        format.json { render :show, status: :ok, location: @intervention }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @intervention.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interventions/1 or /interventions/1.json
  def destroy
    @intervention.destroy

    respond_to do |format|
      format.html { redirect_to interventions_url, notice: "Intervention was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_intervention
      @intervention = Intervention.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def intervention_params
      params.require(:intervention).permit(:Author, :CustomerID, :BuildingID, :BatteryID, :ColumnID, :ElevatorID, :EmployeeID, :Report)
    end
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/interventions/_form.html.erb
<%= form_with(model: intervention, local: true) do |f| %>
  <% if intervention.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(intervention.errors.count, "error") %> prohibited this intervention from being saved:</h2>

      <ul>
      <% intervention.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%#-------  Intervention form -------#%>

  <section>
    <div class="container">

    <%#-------  Step 1 - Customer -------#%>
      <div>
        <div class="card">
          <h4 class="card-header">STEP 1</h4>
          <div class="card-body">
            <div class="card-title">
              <%= f.label :customer_id, "Find a customer" %>
              <select class="custom-select mb-0 mr-sm-0 mb-sm-0"<%= f.select(:CustomerID) do %>>
                <option selected>None</option>
                  <%= @customers.each do |c| %>
                <option value="<%= c.id %>"><%= c.CompanyName %></option>
                <% end %>
              <% end %>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a class="btn btn-primary" id="buttonCustomer">Next</a>
            </div>
        </div>
      </div>


      <%#-------  Step 2 - Building -------#%>
      <div>
        <div id="step2" class="card">
          <h4 class="card-header">STEP 2</h4>
          <div class="card-body">
            <%= f.label :building_id, "Find a building" %>
            <div class="card-title">
            <select class="custom-select mb-0 mr-sm-0 mb-sm-0" <%= f.grouped_collection_select :BuildingID, Customer.order(:CompanyName), :buildings, :CompanyName, :id, :addressBuilding, include_blank: true %>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a class="btn btn-primary" id="buttonBuilding">Next</a>
            </div>
          </div>
        </div>
      </div>


      <%#-------  Step 3 - Battery -------#%>
      <div>
        <div id="step3" class="card">
          <h4 class="card-header">STEP 3</h4>
          <div class="card-body">
          <div class="card-title">
            <%= f.label :battery_id, "Find a battery" %>
            <select class="custom-select mb-0 mr-sm-0 mb-sm-0"<%= f.grouped_collection_select :BatteryID, Building.order(:addressBuilding), :batteries, :addressBuilding, :id, :id, include_blank: true %>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a class="btn btn-primary" id="buttonBattery">Next</a>
            </div>
          </div>
        </div>
      </div>


      <%#-------  Step 4 - Column -------#%>
      <div>
        <div id="step4" class="card">
          <h4 class="card-header">STEP 4</h4>
          <div class="card-body">
          <%= f.label :column_id, "Find a column" %>
            <div class="card-title">
            <select class="custom-select mb-0 mr-sm-0 mb-sm-0"<%= f.grouped_collection_select :ColumnID, Battery.order(:id), :columns, :id, :id, :id, include_blank: true %>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a class="btn btn-primary" id="buttonColumn">Next</a>
            </div>
          </div>
        </div>
      </div>


      <%#-------  Step 5 - Elevator -------#%>
      <div>
        <div id="step5" class="card">
          <h4 class="card-header">STEP 5</h4>
          <div class="card-body">
            <%= f.label :elevator_id, "Find a lift" %>
            <div class="card-title">
              <select class="custom-select mb-0 mr-sm-0 mb-sm-0"<%= f.grouped_collection_select :ElevatorID, Column.order(:id), :elevators, :id, :id, :id, include_blank: true %>
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
              <a class="btn btn-primary" id="buttonElevator">Next</a>
            </div>
          </div>
        </div>
      </div>


      <%#-------  Step 5 - Employee -------#%>
        <div class="card">
          <h4 class="card-header">STEP 6</h4>
          <div class="card-body">
            <div class="card-title">
              <%= f.label :employee_id, "Find an employee" %>
              <select class="custom-select mb-0 mr-sm-0 mb-sm-0"<%= f.select(:EmployeeID) do %>>
                <option selected>None</option>
                  <%= @employee.each do |e| %>
                <option value="<%= e.id %>"><%= e.firstName %> <%= e.lastName %></option>
                <% end %>
              <% end %>
              </select>
            </div>
        </div>
      </div>


      <%#-------  Step 7 - Write Report -------#%>
      <div>
        <div class="card">
          <h4 class="card-header">STEP 7</h4>
          <div class="card-body">
          <div class="card-title">
            <%= f.label :Report, "Write a Report" %>
              <div class="form-floating">
              <textarea class="form-control" id="floatingTextarea"<%= f.text_area :Report %>
              </div>
            </div>
            </div>
        </div>
      </div>


      <%#------- Author -------#%>
      <div class="card">
        <div class="card-header"><%= f.label :Author, "Ticket author ID " %></div>
        <div class="card-body">
        <input type="text" readonly class="form-control-plaintext" id="staticEmail" value= "<%= current_user.id %>" <%= f.text_area :Author%>
        </div>
      </div>

      <%#------- Button -------#%>
      <div class="actions">
        <%= f.submit class: "btn btn-primary btn-lg"%>
        <% end %>
      </div>
  </section>

app/views/interventions/edit.html.erb
<div class="container">
    <h1>Editing Intervention</h1>
    
    <%= render 'form', intervention: @intervention %>
    
    <%= link_to 'Show', @intervention %> |
    <%= link_to 'Back', interventions_path %>
</div>

app/views/interventions/index.html.erb
			<%= render "navbar" %>

			<!-- /PAGE HEADER -->

			<!-- style for the form backgound that's so cooool -->
			<style>
				.formBGRE {
					background-image: url(AdobeStock_122227340.jpeg);
					background-repeat: repeat-x;
				}
			</style>
			<!-- /style for the form backgound that's so cooool -->


    <p id="notice"><%= notice %></p>

	<section class="page">
		<div class="container">

			<div class="card border-light mb-3">
				<div class="card-header">
					<h2>INTERVENTIONS</h2>
				</div>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Customer</th>
								<th>Building</th>
								<th>Battery</th>
								<th>Column</th>
								<th>Elevator</th>
								<th>Employee</th>
								<th>Start</th>
								<th>End</th>
								<th></th>
								<th>Actions</th>
								<th colspan="3"></th>
							</tr>
						</thead>
						<tbody>
							<% @interventions.each do |intervention| %>
								<tr>
								<td><%= intervention.CustomerID %></td>
								<td><%= intervention.BuildingID %></td>
								<td><%= intervention.BatteryID %></td>
								<td><%= intervention.ColumnID %></td>
								<td><%= intervention.ColumnID %></td>
								<td><%= intervention.EmployeeID %></td>
								<td><%= intervention.StartDate %></td>
								<td><%= intervention.EndDate %></td>
								<th>
									<%= link_to intervention, :class => 'btn btn-outline-success' do %>
										<span>Show</span>
									<% end %>
								</th>
								<th>
									<%= link_to edit_intervention_path(intervention), :class => 'btn btn-outline-info' do %>
										<span>Edit</span>
									<% end %>
								</th>
								<td><span class= "btn btn-outline-danger"><%= link_to 'Destroy', intervention, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
								</tr>
							<% end %>
						</tbody>
					</table>
			</div>

			<br>
			<% if user_signed_in? %>
				<%= link_to new_intervention_path, :class => 'btn btn-outline-primary' do %>
					<span>New Intervention</span>
				<% end %>
				<% else %>
					<%= link_to new_user_session_path, :class => 'btn btn-outline-secondary' do %>
						<span>Login before New Intervention</span>
					<% end %>
				<% end %>

		</div>
	</section>


		<!-- FOOTER -->
<footer id="footer" class=" footer navbar-fixed-bottom">
	<div class="container">
		<div class="row">
			<!-- col #1 -->
			<div class="col-md-8">
				<h3 class="letter-spacing-1">WHY US?</h3>
				<!-- Small Description -->
				<p>
					To put it simple, Rocket Elevator truly wants to give people safe and comfortable elevators, those infrastructures are a crucial parts of our daily life and should not be taken lightly. That is why we will always make sure that you get the best possible services in all matters.
				</p>
				<h2>+1 800-887-2497</h2>
			</div>
			<!-- /col #1 -->

			<!-- col #2 -->
			<div class="col-md-4">
				<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

				<!-- Newsletter Form -->
				<p>Subscribe to Our Newsletter to get Important News & Offers</p>
				<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
						<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
						<span class="input-group-btn">
							<button class="btn btn-success" type="submit">Subscribe</button>
						</span>
					</div>
				</form>
				<!-- /Newsletter Form -->
			</div>
			<!-- /col #2 -->
		</div>
	</div>

	<div class="copyright">
		<div class="container">
			<ul class="float-right m-0 list-inline mobile-block">
				<li><a href="#">Terms &amp; Conditions</a></li>
				<li>&bull;</li>
				<li><a href="#">Privacy</a></li>
			</ul>
			&copy; All Rights Reserved, Rocket Elevator LTD
		</div>
	</div>
</footer>
<!-- /FOOTER -->

app/views/interventions/new.html.erb
<%= render "navbar" %>

<section class="page-header">
	<div class="container">

	<h1>NEW INTERVENTION</h1>

	</div>
</section>
<!-- /PAGE HEADER -->

<!-- style for the form backgound that's so cooool -->
<style>
	.formBGRE {
		background-image: url(AdobeStock_122227340.jpeg);
		background-repeat: repeat-x;
	}
</style>
<!-- /style for the form backgound that's so cooool -->



<%= render 'form', intervention: @intervention %>


<!-- FOOTER -->
<footer id="footer" class=" footer navbar-fixed-bottom">
	<div class="container">
		<div class="row">
			<!-- col #1 -->
			<div class="col-md-8">
				<h3 class="letter-spacing-1">WHY US?</h3>
				<!-- Small Description -->
				<p>
					To put it simple, Rocket Elevator truly wants to give people safe and comfortable elevators, those infrastructures are a crucial parts of our daily life and should not be taken lightly. That is why we will always make sure that you get the best possible services in all matters.
				</p>
				<h2>+1 800-887-2497</h2>
			</div>
			<!-- /col #1 -->

			<!-- col #2 -->
			<div class="col-md-4">
				<h3 class="letter-spacing-1">KEEP IN TOUCH</h3>

				<!-- Newsletter Form -->
				<p>Subscribe to Our Newsletter to get Important News & Offers</p>
				<form class="validate" action="php/newsletter.php" method="post" data-success="Subscribed! Thank you!" data-toastr-position="bottom-right">
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-envelope"></i></span>
						<input type="email" id="email" name="email" class="form-control required" placeholder="Enter your Email">
						<span class="input-group-btn">
							<button class="btn btn-success" type="submit">Subscribe</button>
						</span>
					</div>
				</form>
				<!-- /Newsletter Form -->
			</div>
			<!-- /col #2 -->
		</div>
	</div>

	<div class="copyright">
		<div class="container">
			<ul class="float-right m-0 list-inline mobile-block">
				<li><a href="#">Terms &amp; Conditions</a></li>
				<li>&bull;</li>
				<li><a href="#">Privacy</a></li>
			</ul>
			&copy; All Rights Reserved, Rocket Elevator LTD
		</div>
	</div>
</footer>
<!-- /FOOTER -->

app/views/interventions/show.html.erb
<div class="container">
    <p id="notice"><%= notice %></p>

    <span class= "btn btn-outline-info"><%= link_to 'Edit', edit_intervention_path(@intervention) %></span>
    <span class= "btn btn-outline-secondary"><%= link_to 'Back', interventions_path %></span>
</div>